### Environment variables
@baseUrl = http://localhost:8080
@username = aaa
@password = aaa
@client_id = your_client_id
@client_secret = your_client_secret


### Login to get tokens
POST {{baseUrl}}/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username={{username}}&password={{password}}&client_id={{client_id}}&client_secret={{client_secret}}&scope=openid profile email

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
    client.global.set("id_token", response.body.id_token);
%}


### Get User Info
GET {{baseUrl}}/userinfo
Authorization: Bearer {{access_token}}


### Refresh Token
POST {{baseUrl}}/refresh
Content-Type: application/json

{
  "refresh_token": "{{refresh_token}}"
}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}
