### Environment variables
@baseUrl = http://localhost:8080
@username = a
@password = a
@client_id = your_client_id
@client_secret = your_client_secret

### OpenID Configuration
GET {{baseUrl}}/.well-known/openid-configuration

### JWKS
GET {{baseUrl}}/jwks.json


### Client Registration
# @name register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "client_id": "{{client_id}}",
  "client_secret": "{{client_secret}}"
}

> {%
    client.global.set("client_id", "{{client_id}}");
    client.global.set("client_secret", "{{client_secret}}");
%}


### Login to get tokens
# @name login
POST {{baseUrl}}/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username={{username}}&password={{password}}&client_id={{client_id}}&client_secret={{client_secret}}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
  %}

### Get User Info
GET {{baseUrl}}/userinfo
Authorization: Bearer {{access_token}}

### Refresh Token
POST {{baseUrl}}/refresh
Content-Type: application/json

{
  "refresh_token": "{{refresh_token}}"
}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Invalid Refresh Token (for testing error handling)
POST {{baseUrl}}/refresh
Content-Type: application/json

{
  "refresh_token": "invalid_refresh_token"
}
